package me.fzzyhmstrs.tridents_n_stuff.material

import net.fabricmc.yarn.constants.MiningLevels
import net.minecraft.item.Items
import net.minecraft.recipe.Ingredient
import net.minecraft.util.Identifier

object TnsTridentMaterialsConfig {

    val SLUMBERING = ValidatedToolMaterial.Builder()
        .durability(650)
        .miningSpeedMultiplier(8f)
        .attackDamage(9f)
        .miningLevel(MiningLevels.DIAMOND)
        .enchantability(15)
        .repairIngredient(Identifier("nautilus_shell"))
        .build()
    val STORMSEEKER = ValidatedToolMaterial.Builder()
        .durability(2250)
        .miningSpeedMultiplier(8f)
        .attackDamage(11f)
        .miningLevel(MiningLevels.DIAMOND)
        .enchantability(15)
        .repairIngredient(Identifier("conduit"))
        .build()
    val DESECRATOR = ValidatedToolMaterial.Builder()
        .durability(2250)
        .miningSpeedMultiplier(8f)
        .attackDamage(13f)
        .miningLevel(MiningLevels.DIAMOND)
        .enchantability(25)
        .repairIngredient(Identifier("wither_skeleton_skull"))
        .build()
    val ECHO = ValidatedToolMaterial.Builder()
        .durability(2250)
        .miningSpeedMultiplier(8f)
        .attackDamage(9f)
        .miningLevel(MiningLevels.DIAMOND)
        .enchantability(19)
        .repairIngredient(Identifier("echo_shard"))
        .build()
    val STELLARIS = ValidatedToolMaterial.Builder()
        .durability(2250)
        .miningSpeedMultiplier(8f)
        .attackDamage(11f)
        .miningLevel(MiningLevels.DIAMOND)
        .enchantability(25)
        .repairIngredient(Identifier("crying_obsidian"))
        .build()
    val SANGUINE = ValidatedToolMaterial.Builder()
        .durability(2250)
        .miningSpeedMultiplier(8f)
        .attackDamage(13f)
        .miningLevel(MiningLevels.DIAMOND)
        .enchantability(10)
        .repairIngredient(Identifier("totem_of_undying"))
        .build()

    val FRENZIED = ValidatedToolMaterial.Builder()
        .durability(350)
        .miningSpeedMultiplier(6f)
        .attackDamage(6f)
        .miningLevel(MiningLevels.DIAMOND)
        .enchantability(20)
        .repairIngredient(Identifier("redstone_block"))
        .build()
    val ANCIENT = ValidatedToolMaterial.Builder()
        .durability(2031)
        .miningSpeedMultiplier(10f)
        .attackDamage(11f)
        .miningLevel(MiningLevels.NETHERITE)
        .enchantability(22)
        .repairIngredient(Identifier("netherite_scrap"))
        .build()
    val OCEANIC = ValidatedToolMaterial.Builder()
        .durability(350)
        .miningSpeedMultiplier(6f)
        .attackDamage(9f)
        .miningLevel(MiningLevels.DIAMOND)
        .enchantability(20)
        .repairIngredient(Identifier("nautilus_shell"))
        .build()
    val HOLY = ValidatedToolMaterial.Builder()
        .durability(350)
        .miningSpeedMultiplier(6f)
        .attackDamage(9f)
        .miningLevel(MiningLevels.DIAMOND)
        .enchantability(15)
        .repairIngredient(Identifier("golden_apple"))
        .build()
    val FARSHOT = ValidatedToolMaterial.Builder()
        .durability(350)
        .miningSpeedMultiplier(6f)
        .attackDamage(9f)
        .miningLevel(MiningLevels.DIAMOND)
        .enchantability(25)
        .repairIngredient(Identifier("phantom_membrane"))
        .build()
}