package me.fzzyhmstrs.tridents_n_stuff.material

import me.fzzyhmstrs.fzzy_config.validated_field.ValidatedToolMaterial
import net.fabricmc.yarn.constants.MiningLevels
import net.minecraft.item.Items
import net.minecraft.recipe.Ingredient

object TnsTridentMaterialsConfig {

    val STORMSEEKER = ValidatedToolMaterial.Builder()
        .durability(650)
        .miningSpeedMultiplier(8f)
        .attackDamage(11f)
        .miningLevel(MiningLevels.DIAMOND)
        .enchantability(15)
        .repairIngredient(Ingredient.ofItems(Items.CONDUIT))
        .build()
    val DESECRATOR = ValidatedToolMaterial.Builder()
        .durability(500)
        .miningSpeedMultiplier(8f)
        .attackDamage(13f)
        .miningLevel(MiningLevels.DIAMOND)
        .enchantability(25)
        .repairIngredient(Ingredient.ofItems(Items.WITHER_SKELETON_SKULL))
        .build()
    val ECHO = ValidatedToolMaterial.Builder()
        .durability(750)
        .miningSpeedMultiplier(8f)
        .attackDamage(9f)
        .miningLevel(MiningLevels.DIAMOND)
        .enchantability(19)
        .repairIngredient(Ingredient.ofItems(Items.ECHO_SHARD))
        .build()
    val STELLARIS = ValidatedToolMaterial.Builder()
        .durability(500)
        .miningSpeedMultiplier(8f)
        .attackDamage(11f)
        .miningLevel(MiningLevels.DIAMOND)
        .enchantability(25)
        .repairIngredient(Ingredient.ofItems(Items.CRYING_OBSIDIAN))
        .build()
    val SANGUINE = ValidatedToolMaterial.Builder()
        .durability(850)
        .miningSpeedMultiplier(8f)
        .attackDamage(13f)
        .miningLevel(MiningLevels.DIAMOND)
        .enchantability(10)
        .repairIngredient(Ingredient.ofItems(Items.TOTEM_OF_UNDYING))
        .build()

    val FRENZIED = ValidatedToolMaterial.Builder()
        .durability(350)
        .miningSpeedMultiplier(6f)
        .attackDamage(6f)
        .miningLevel(MiningLevels.DIAMOND)
        .enchantability(20)
        .repairIngredient(Ingredient.ofItems(Items.REDSTONE_BLOCK))
        .build()
    val ANCIENT = ValidatedToolMaterial.Builder()
        .durability(350)
        .miningSpeedMultiplier(10f)
        .attackDamage(11f)
        .miningLevel(MiningLevels.NETHERITE)
        .enchantability(22)
        .repairIngredient(Ingredient.ofItems(Items.NETHERITE_SCRAP))
        .build()
    val OCEANIC = ValidatedToolMaterial.Builder()
        .durability(350)
        .miningSpeedMultiplier(6f)
        .attackDamage(9f)
        .miningLevel(MiningLevels.DIAMOND)
        .enchantability(20)
        .repairIngredient(Ingredient.ofItems(Items.NAUTILUS_SHELL))
        .build()
    val HOLY = ValidatedToolMaterial.Builder()
        .durability(350)
        .miningSpeedMultiplier(6f)
        .attackDamage(9f)
        .miningLevel(MiningLevels.DIAMOND)
        .enchantability(15)
        .repairIngredient(Ingredient.ofItems(Items.GOLDEN_APPLE))
        .build()
    val FARSHOT = ValidatedToolMaterial.Builder()
        .durability(350)
        .miningSpeedMultiplier(6f)
        .attackDamage(9f)
        .miningLevel(MiningLevels.DIAMOND)
        .enchantability(25)
        .repairIngredient(Ingredient.ofItems(Items.PHANTOM_MEMBRANE))
        .build()
}